In [58]:
import numpy as np
import gensim
import os
import re

from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from gensim import corpora

from gensim.models.ldamulticore import LdaMulticore

import pandas as pd
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

""" Import Statements """

# Classics
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors
from sklearn.decomposition import PCA

# Import Statements
from sklearn.pipeline import Pipeline

from sklearn.linear_model import SGDClassifier#stochastic gradient descent
from sklearn.feature_extraction.text import TfidfVectorizer

# Experiment Management
from sklearn.model_selection import GridSearchCV

from sklearn.decomposition import TruncatedSVD

import spacy
nlp = spacy.load("en_core_web_md")

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Sprint Challenge
## *Data Science Unit 4 Sprint 1*

After a week of Natural Language Processing, you've learned some cool new stuff: how to process text, how turn text into vectors, and how to model topics from documents. Apply your newly acquired skills to one of the most famous NLP datasets out there: [Yelp](https://www.yelp.com/dataset/challenge). As part of the job selection process, some of my friends have been asked to create analysis of this dataset, so I want to empower you to have a head start.  

The real dataset is massive (almost 8 gigs uncompressed). I've sampled the data for you to something more managable for the Sprint Challenge. You can analyze the full dataset as a stretch goal or after the sprint challenge. As you work on the challenge, I suggest adding notes about your findings and things you want to analyze in the future.

## Challenge Objectives
*Successfully complete these all these objectives to earn a 2. There are more details on each objective further down in the notebook.*
* <a href="#p1">Part 1</a>: Write a function to tokenize the yelp reviews
* <a href="#p2">Part 2</a>: Create a vector representation of those tokens
* <a href="#p3">Part 3</a>: Use your tokens in a classification model on yelp rating
* <a href="#p4">Part 4</a>: Estimate & Interpret a topic model of the Yelp reviews

In [20]:
import pandas as pd

yelp = pd.read_json('./data/review_sample.json', lines=True)

In [21]:
yelp.head()

business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id  
0  n1LM36qNg4rqGXIcvVXv8w  
1  5CgjjDAic2-FAvCtiHpytA  
2  BdV-cf3LScmb8kZ7iiBcMA  
3  cZZnBqh4gAEy4CdNvJailQ  
4  n9QO4ClYAS7h9fpQwa5bhA

## Part 1: Tokenize Function
<a id="#p1"></a>

Complete the function `tokenize`. Your function should
- accept one document at a time
- return a list of tokens

You are free to use any method you have learned this week.

In [22]:
yelp.shape

(10000, 9)

In [23]:
def tokenize(doc):
    return [token for token in simple_preprocess(doc)]

yelp['tokens'] = yelp['text'].apply(lambda x: tokenize(x))
yelp.head()

business_id  cool                date  funny  \
0  nDuEqIyRc8YKS1q1fX0CZg     1 2015-03-31 16:50:30      0   
1  eMYeEapscbKNqUDCx705hg     0 2015-12-16 05:31:03      0   
2  6Q7-wkCPc1KF75jZLOTcMw     1 2010-06-20 19:14:48      1   
3  k3zrItO4l9hwfLRwHBDc9w     3 2010-07-13 00:33:45      4   
4  6hpfRwGlOzbNv7k5eP9rsQ     1 2018-06-30 02:30:01      0   

                review_id  stars  \
0  eZs2tpEJtXPwawvHnHZIgQ      1   
1  DoQDWJsNbU0KL1O29l_Xug      4   
2  DDOdGU7zh56yQHmUnL1idQ      3   
3  LfTMUWnfGFMOfOIyJcwLVA      1   
4  zJSUdI7bJ8PNJAg4lnl_Gg      4   

                                                text  useful  \
0  BEWARE!!! FAKE, FAKE, FAKE....We also own a sm...      10   
1  Came here for lunch Togo. Service was quick. S...       0   
2  I've been to Vegas dozens of times and had nev...       2   
3  We went here on a night where they closed off ...       5   
4  3.5 to 4 stars\n\nNot bad for the price, $12.9...       5   

                  user_id                                             tokens  
0  n1LM36qNg4rqGXIcvVXv8w  [beware, fake, fake, fake, we, also, own, smal...  
1  5CgjjDAic2-FAvCtiHpytA  [came, here, for, lunch, togo, service, was, q...  
2  BdV-cf3LScmb8kZ7iiBcMA  [ve, been, to, vegas, dozens, of, times, and, ...  
3  cZZnBqh4gAEy4CdNvJailQ  [we, went, here, on, night, where, they, close...  
4  n9QO4ClYAS7h9fpQwa5bhA  [to, stars, not, bad, for, the, price, for, lu...

## Part 2: Vector Representation
<a id="#p2"></a>
1. Create a vector representation of the reviews
2. Write a fake review and query for the 10 most similiar reviews, print the text of the reviews. Do you notice any patterns?
    - Given the size of the dataset, it will probably be best to use a `NearestNeighbors` model for this. 

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

# create the transformer
vectorizer = CountVectorizer(stop_words='english')

# tokenize and build vocab
vectorizer.fit(yelp['text'])


# Create a Vocabulary
# The vocabulary establishes all of the possible words that we might use.
vectorizer.vocabulary_

# The vocabulary dictionary does not represent the counts of words!!
dtm = vectorizer.transform(yelp['text'])

In [25]:
# Get Word Counts for each document
dtmdf = pd.DataFrame(dtm.todense(), columns = vectorizer.get_feature_names())
dtmdf.head()

00  000  001695  007  00a  00am  00ish  00pm  01  011802  02  02022015  \
0   0    0       0    0    0     0      0     0   0       0   0         0   
1   0    0       0    0    0     0      0     0   0       0   0         0   
2   0    0       0    0    0     0      0     0   0       0   0         0   
3   0    0       0    0    0     0      0     0   0       0   0         0   
4   0    0       0    0    0     0      0     0   0       0   0         0   

   02pm  03  04  05  05pm  06  07  08  09  0d  0mph  10  100  1000  1001  \
0     0   0   0   0     0   0   0   0   0   0     0   0    0     0     0   
1     0   0   0   0     0   0   0   0   0   0     0   0    0     0     0   
2     0   0   0   0     0   0   0   0   0   0     0   0    0     0     0   
3     0   0   0   0     0   0   0   0   0   0     0   0    0     0     0   
4     0   0   0   0     0   0   0   0   0   0     0   0    0     0     0   

   100k  100lb  100s  100th  100x  101  102  1026  1030am  104  105  106  \
0     0      0     0      0     0    0    0     0       0    0    0    0   
1     0      0     0      0     0    0    0     0       0    0    0    0   
2     0      0     0      0     0    0    0     0       0    0    0    0   
3     0      0     0      0     0    0    0     0       0    0    0    0   
4     0      0     0      0     0    0    0     0       0    0    0    0   

   106lb  107  108  109  1096  1099  10am  10k  10min  10mins  10news  10p  \
0      0    0    0    0     0     0     0    0      0       0       0    0   
1      0    0    0    0     0     0     0    0      0       0       0    0   
2      0    0    0    0     0     0     0    0      0       0       0    0   
3      0    0    0    0     0     0     0    0      0       0       0    0   
4      0    0    0    0     0     0     0    0      0       0       0    0   

   10pm  10th  10times  10x  10years  10yrs  11  110  110th  111  1115a  1130  \
0     0     0        0    0        0      0   0    0      0    0      0     0   
1     0     0        0    0        0      0   0    0      0    0      0     0   
2     0     0        0    0        0      0   0    0      0    0      0     0   
3     0     0        0    0        0      0   0    0      0    0      0     0   
4     0     0        0    0        0      0   0    0      0    0      0     0   

   115  117  119  11a  11am  11ish  11pm  12  120  1200  1221  123  123lbs  \
0    0    0    0    0     0      0     0   0    0     0     0    0       0   
1    0    0    0    0     0      0     0   0    0     0     0    0       0   
2    0    0    0    0     0      0     0   0    0     0     0    0       0   
3    0    0    0    0     0      0     0   0    0     0     0    0       0   
4    0    0    0    0     0      0     0   1    0     0     0    0       0   

   1245p  125  1260  129  12am  12k  12months  12oz  12pk  12pm  12th  \
0      0    0     0    0     0    0         0     0     0     0     0   
1      0    0     0    0     0    0         0     0     0     0     0   
2      0    0     0    0     0    0         0     0     0     0     0   
3      0    0     0    0     0    0         0     0     0     0     0   
4      0    0     0    0     0    0         0     0     0     0     0   

   12か所のコーナーのステアリングさばきは実にお見事でとてもいい体験になりました  13  130  131  135  139  13th  14  \
0                                        0   0    0    0    0    0     0   0   
1                                        0   0    0    0    0    0     0   0   
2                                        0   0    0    0    0    0     0   0   
3                                        0   0    0    0    0    0     0   0   
4                                        0   0    0    0    0    0     0   0   

   140  1400  14000  141  144  1440  145  149  14oz  14th  15  150  1500  \
0    0     0      0    0    0     0    0    0     0     0   0    0     0   
1    0     0      0    0    0     0    0    0     0     0   0    0     0   
2    0     0      0    0    0     0    0    0     0  

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate vectorizer object
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)

# Create a vocabulary and get word counts per document
dtm = tfidf.fit_transform(yelp['text'])
#dtm = tfidf.transform(new_data)

# Print word counts

# Get feature names to use as dataframe column headers

# View Feature Matrix as DataFrame
docs = pd.DataFrame(dtm.todense(), columns = tfidf.get_feature_names())
docs.head()

00  000  00pm   07   10  100  1000  101  10pm   11  110  11am  11pm  \
0  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0   0.0   0.0   
1  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0   0.0   0.0   
2  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0   0.0   0.0   
3  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0   0.0   0.0   
4  0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0   0.0  0.0  0.0   0.0   0.0   

         12  120   13   14        15  150   16   17   18   19  1pm  1st  \
0  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.000000  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.145412  0.0  0.0  0.0  0.130277  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

         20  200  2006  2011  2012  2013  2014  2015  2016  2017  2018   21  \
0  0.100258  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0   
1  0.000000  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0   
2  0.000000  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0   
3  0.000000  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0   
4  0.000000  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0   

    22   23        24        25  250   26   27   28   29  2nd  2pm   30  300  \
0  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.086242  0.077824  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   30am  30pm   35   39  3pm  3rd   40  400   45   48   49  4pm  4th   50  \
0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   500   55  5pm   60  600   65  6pm        70   75  7pm  7th   80   88  8pm  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.155579  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  0.0   

    90   95        99  9pm  ability  able  absolute  absolutely   ac  accent  \
0  0.0  0.0  0.000000  0.0      0.0   0.0       0.0         0.0  0.0     0.0   
1  0.0  0.0  0.000000  0.0      0.0   0.0       0.0         0.0  0.0     0.0   
2  0.0  0.0  0.000000  0.0      0.0   0.0       0.0         0.0  0.0     0.0   
3  0.0  0.0  0.000000  0.0      0.0   0.0       0.0         0.0  0.0     0.0   
4  0.0  0.0  0.167883  0.0      0.0   0.0       0.0         0.0  0.0     0.0   

   accept  acceptable  accepted  access  accessible  accessories  accident  \
0     0.0         0.0       0.0     0.0         0.0          0.0       0.0   
1     0.0         0.0       0.0     0.0         0.0          0.0       0.0   
2     0.0         0.0       0.0     0.0         0.0          0.0       0.0   
3     0.0         0.0       0.0     0.0         0.0          0.0       0.0   
4     0.0         0.0       0.0     0.0         0.0          0.0       0.0   

   accidentally  accommodate  accommodated  accommodating  accomodating  \
0           0.0          0.0           0.0            0.0           0.0   
1           0.0          0.0           0.0            0.0           0.0   
2           0.0          0.

In [44]:
# Instantiate
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')

# Fit on TF-IDF Vectors
nn.fit(dtm.todense())

NearestNeighbors(algorithm='ball_tree', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [45]:
# Query Using kneighbors 
nn.kneighbors(dtm.todense()[0])

(array([[0.        , 1.        , 1.        , 1.25325603, 1.25954602]]),
 array([[   0, 6311, 6204, 2131, 3276]], dtype=int64))

In [46]:
yelp.sample(2)

business_id  cool                date  funny  \
711   _cjPEH9wXhKS-HQe_U3M4Q     0 2015-07-20 01:35:07      0   
4297  e13SEvJud_vgeDR_doL4sQ     0 2013-07-29 21:07:28      0   

                   review_id  stars  \
711   ukOt3ry_xXt6YmPqJA86sg      5   
4297  uwoysbaEnQBABnnSVzi0eg      4   

                                                   text  useful  \
711   I went for the first time today.  Wow, the fre...       0   
4297  Stopped here for a QUICK bite before our show....       1   

                     user_id  \
711   7GS60aGKil36XCO4vLGDgQ   
4297  QraRy2Y1RYSRbH7WJN5_cw   

                                                 tokens  
711   [went, for, the, first, time, today, wow, the,...  
4297  [stopped, here, for, quick, bite, before, our,...

In [47]:
yelp['text'].iloc[8339]

"I really enjoy the spiciness of the Arizona burger.\n\nWith today's meal we got a little confused and mis-ordered something but Jalissa, the manager, was more than eager to fix it for us.  There was a lot of positive energy from the staff and they kept things moving smoothly.\n\nI'm impressed with both the food and, especially, the service.  My biggest problem is being careful to not over-order and get the shake and the fries and the everything else.\n\nOverall, I've been very pleased with my meals at this location."

In [48]:
#tfidf = TfidfVectorizer(stop_words='english', max_features=5000)

fake_review = ['''I thought the service was excellent, I really liked the food. I wish the price was more reasonable, but overall the experience was good.''']
new = tfidf.transform(fake_review)
nn.kneighbors(new.todense())

(array([[1.        , 1.        , 1.15384855, 1.17164522, 1.18575431]]),
 array([[6204, 6311, 3693, 1781, 3062]], dtype=int64))

In [53]:
yelp['text'].iloc[1781]

'Excellent place to go to. Our waitress Laura was great in taking care of me and my friend. The food overall is pretty good and not expensive. We loved our overall experience and we hope to be back soon.'

In [52]:
yelp['text'].iloc[3062]

'Excellent place!, excellent service, good food, expect to pay about 20.00 for a burger but its an experience and its vegas!!'

## Part 3: Classification
<a id="#p3"></a>
Your goal in this section will be to predict `stars` from the review dataset. 

1. Create a piepline object with a sklearn `CountVectorizer` or `TfidfVector` and any sklearn classifier. Use that pipeline to estimate a model to predict `stars`. Use the Pipeline to predict a star rating for your fake review from Part 2. 
2. Tune the entire pipeline with a GridSearch

## Part 4: Topic Modeling

Let's find out what those yelp reviews are saying! :D

1. Estimate a LDA topic model of the review text
2. Create 1-2 visualizations of the results
    - You can use the most important 3 words of a topic in relevant visualizations. Refer to yesterday's notebook to extract. 
3. In markdown, write 1-2 paragraphs of analysis on the results of your topic model

__*Note*__: You can pass the DataFrame column of text reviews to gensim. You do not have to use a generator.

In [55]:
# Create Pipeline

vect = TfidfVectorizer(stop_words='english')#instantiate vectorizer
sgdc = SGDClassifier()#instantiate classifier

pipe = Pipeline([('vect', vect), ('clf', sgdc)])#put objects in pipe#the last item in pipeline, should have fit command
#vectorizor, classifier

# Fit Pipeline
#pipe.fit(data.data, data.target)
pipe.fit(yelp['text'], yelp['stars'])

C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
...m_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False))])

In [56]:
pipe.predict(['I thought the service was excellent, I really liked the food. I wish the price was more reasonable, but overall the experience was good.'])

array([4], dtype=int64)

In [59]:
parameters = {
    'vect__max_df': (0.5, 0.75, 1.0),#word appears than more than 50% of documents, excluded, 
    #max df is a parameter of tfidf
    #vect__min_df works similarly must be inside at least 2% 
    #'vect__min_df': (.02, .05),
    'vect__max_features':(500, 500, 1000),#total number of words tfidf will learn after above parameters
    'clf__max_iter':(2, 10, 10)#number of times makes a pass search 
    #max_iter SGDClassifier
}
grid_search = GridSearchCV(pipe,parameters, cv=5, n_jobs=-1, verbose=1)
grid_search.fit(yelp['text'], yelp['stars'])

Fitting 5 folds for each of 27 candidates, totalling 135 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   21.0s
[Parallel(n_jobs=-1)]: Done 135 out of 135 | elapsed:  1.1min finished
C:\Users\lilyx\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
...m_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False))]),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'vect__max_df': (0.5, 0.75, 1.0), 'vect__max_features': (500, 500, 1000), 'clf__max_iter': (2, 10, 10)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [60]:
pipe.predict(['I thought the service was excellent, I really liked the food. I wish the price was more reasonable, but overall the experience was good.'])

array([4], dtype=int64)

#### Stretch Goals

Complete one of more of these to push your score towards a three: 
* Incorporate named entity recognition into your analysis
* Compare vectorization methods in the classification section
* Analyze more (or all) of the yelp dataset - this one is v. hard. 
* Use a generator object on the reviews file - this would help you with the analyzing the whole dataset.
* Incorporate any of the other yelp dataset entities in your analysis (business, users, etc.)

In [118]:
import spacy#how to do everything above using spacy
from spacy.tokenizer import Tokenizer

nlp = spacy.load("en_core_web_md")
# Tokenizer
tokenizer = Tokenizer(nlp.vocab)
tokens = []

""" Update those tokens w/o stopwords"""
for doc in tokenizer.pipe(yelp['text'], batch_size=500):
    doc_tokens = []
    
    for token in doc:
        if (token.is_stop == False) & (token.is_punct == False):
            doc_tokens.append(token.text.lower())
    tokens.append(doc_tokens)
            
yelp['tokens2'] = tokens

In [119]:
# A Dictionary Representation of all the words in our corpus
id2word = corpora.Dictionary(yelp['tokens2'])#fit portion of vectorizor
corpus = [id2word.doc2bow(text) for text in yelp['tokens2']]

In [120]:
lda = LdaMulticore(corpus=corpus,
                   id2word=id2word,
                   random_state=723812,#for reproducability not very stable, different results
                   num_topics = 15,
                   passes=10,
                   workers=4#multi-core
                  )

lda.print_topics()#topics are list of tuples, id of topic, and probability * word

[(0,
  '0.019*"\n\n" + 0.016*" " + 0.006*"good" + 0.006*"like" + 0.004*"place" + 0.004*"got" + 0.003*"time" + 0.003*"don\'t" + 0.003*"didn\'t" + 0.002*"told"'),
 (1,
  '0.023*"\n\n" + 0.008*"food" + 0.007*"good" + 0.007*" " + 0.007*"chicken" + 0.007*"like" + 0.006*"great" + 0.005*"place" + 0.005*"little" + 0.004*"\n"'),
 (2,
  '0.021*" " + 0.018*"\n\n" + 0.007*"place" + 0.006*"food" + 0.006*"\n" + 0.005*"it\'s" + 0.004*"good" + 0.003*"told" + 0.003*"service" + 0.003*"didn\'t"'),
 (3,
  '0.028*"\n\n" + 0.006*"it\'s" + 0.005*"like" + 0.005*"place" + 0.004*"good" + 0.004*" " + 0.004*"people" + 0.004*"got" + 0.004*"food" + 0.003*"went"'),
 (4,
  '0.011*"\n" + 0.007*"time" + 0.007*"\n\n" + 0.006*"service" + 0.006*"place" + 0.005*"food" + 0.005*"good" + 0.005*"best" + 0.004*"like" + 0.004*"i\'ve"'),
 (5,
  '0.068*" " + 0.009*"\n\n" + 0.008*"\n" + 0.006*"good" + 0.005*"food" + 0.005*"like" + 0.005*"time" + 0.005*"great" + 0.004*"place" + 0.004*"service"'),
 (6,
  '0.026*"\n" + 0.007*"\n\n" + 

In [121]:
words = [re.findall(r'"([^"]*)"',t[1]) for t in lda.print_topics()]#cleaning
topics = [' '.join(t[0:5]) for t in words]
for t in topics:
    print(t)
    print('\n')
#print(topics[0])#typically use the first 3-5 words for visualization purposes



   good like place




 food good   chicken


  

 place food 





 it's like place good



 time 

 service place


  

 
 good food



 

 place got it's




   de good la




 great place food like


  

 
 good service


  

 food place service




 like don't i've time


food best service place love


  

 great place like




 great place food best




In [ ]:
import pyLDAvis.gensim

pyLDAvis.enable_notebook()
pyLDAvis.gensim.prepare(lda, corpus, id2word)